### ISSUE TITLE
Docker EE 2.0 (UCP) : The PVC automatically went in " Lost " state after few minutes.

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#364] opened 2018-10-12 13:01 UTC
I am consistently observed that the state of PVC is getting changed from Bound to Lost after few minutes.

Following is console output - 

1. When I created SC, PVC, POD

[root@CSSOSBE03-B11 ~]# kubectl get pv,pvc,pod
NAME                                              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM               STORAGECLASS   REASON    AGE
pv/demosc6-e0bb66c9-cdf7-11e8-a0ae-0242ac110010   20Gi       RWO            Delete           Bound     default/pvcclaim7   demosc6                  1m

NAME            STATUS    VOLUME                                         CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc/pvcclaim6   Lost      demosc5-a7e8483a-cd6b-11e8-a0ae-0242ac110010   0                         demosc5        16h
pvc/pvcclaim7   **Bound**     demosc6-e0bb66c9-cdf7-11e8-a0ae-0242ac110010   20Gi       RWO            demosc6        1m

NAME        READY     STATUS    RESTARTS   AGE
po/mypod6   1/1       Running   0          16h
po/mypod7   1/1       Running   0          21s

2. After few minutes -

[root@CSSOSBE03-B11 ~]# kubectl get pv,pvc,pod
NAME            STATUS    VOLUME                                         CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc/pvcclaim6   Lost      demosc5-a7e8483a-cd6b-11e8-a0ae-0242ac110010   0                         demosc5        16h
pvc/pvcclaim7   **Lost**      demosc6-e0bb66c9-cdf7-11e8-a0ae-0242ac110010   0                         demosc6        7m

NAME        READY     STATUS    RESTARTS   AGE
po/mypod6   1/1       Running   0          16h
po/mypod7   1/1       Running   0          6m

dory logs snippet - 

04:22:17 provisioner.go:237: statusLogger: provision chains=0, delete chains=0, parked chains=0, ids tracked=0, connection=valid
04:22:22 provisioner.go:237: statusLogger: provision chains=0, delete chains=0, parked chains=0, ids tracked=0, connection=valid
04:22:26 volume.go:92: updatedVol event: pv:demosc6-e0bb66c9-cdf7-11e8-a0ae-0242ac110010 phase:Bound (reclaim policy:Delete) - skipping
04:22:26 claim.go:96: updatedClaim: pvc pvcclaim6 current phase=Lost
04:22:26 claim.go:96: updatedClaim: pvc pvcclaim7 current phase=Bound
04:22:26 provisioner.go:129: sendUpdate: pvc:pvcclaim7 (e0bb66c9-cdf7-11e8-a0ae-0242ac110010) phase:Bound
04:22:26 provisioner.go:147: send: skipping e0bb66c9-cdf7-11e8-a0ae-0242ac110010, not in map
04:22:26 provisioner.go:129: sendUpdate: pvc:pvcclaim6 (a7e8483a-cd6b-11e8-a0ae-0242ac110010) phase:Lost
04:22:26 provisioner.go:147: send: skipping a7e8483a-cd6b-11e8-a0ae-0242ac110010, not in map
04:22:26 provisioner.go:135: sendUpdate: pv:demosc6-e0bb66c9-cdf7-11e8-a0ae-0242ac110010 (e1152d0b-cdf7-11e8-a0ae-0242ac110010) phase:Bound
04:22:26 provisioner.go:147: send: skipping e1152d0b-cdf7-11e8-a0ae-0242ac110010, not in map
04:22:27 provisioner.go:237: statusLogger: provision chains=0, delete chains=0, parked chains=0, ids tracked=0, connection=valid

**Comment by imran-ansari** [comment] 2018-10-16 02:41
Could you please attach Docker logs?

**Comment by farhan7500** [comment] 2018-10-26 11:56
@imran-ansari, @wdurairaj @nilangekarss : I tried recreating another issue but ended up reproducing this one.

Here are the logs and details:
```
[root@openshift-master-node1 ~]# sudo oc get sc,pvc,pod
NAME                         PROVISIONER   AGE
storageclasses/sc-test8      hpe.com/hpe   87d
storageclasses/sc1           hpe.com/hpe   35d
storageclasses/sc1-farhan8   hpe.com/hpe   2h
storageclasses/sc2           hpe.com/hpe   1d

NAME               STATUS    VOLUME                                             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc/pvc-test8      Bound     sc-test8-82681d06-9409-11e8-b732-c4346bc12918      16Gi       RWO            sc-test8       87d
pvc/pvc1           Bound     sc1-84dcc4f2-bd83-11e8-b732-c4346bc12918           20Gi       RWO            sc1            35d
pvc/pvc1-farhan8   Lost      sc1-farhan8-305cc98d-d900-11e8-b732-c4346bc12918   0                         sc1-farhan8    2h
pvc/pvc2           Bound     sc1-9ed45917-c259-11e8-b732-c4346bc12918           20Gi       RWO            sc1            28d
pvc/pvc22          Bound     sc2-5ae0122e-d847-11e8-b732-c4346bc12918           20Gi       RWO            sc2            1d

NAME                          READY     STATUS    RESTARTS   AGE
po/docker-registry-3-lcdst    1/1       Running   82         98d
po/pod-4                      1/1       Running   0          28d
po/pod1-new-farhan8           1/1       Running   0          2h
po/pod22                      1/1       Running   0          1d
po/registry-console-1-876b7   1/1       Running   73         111d
po/router-9-m4pdb             1/1       Running   12         88d

```

The PVC has gone into 'Lost' State.

Please find the logs at 15.218.171.250:/home/ftpuser/Farhan/lost_pvc.zip
Attaching here was not possible because of the large size of logs

Setup Details:
```
FTC Setup (16.78.26.18 Jump Station)
Master: 10.50.9.15 (root/hpinvent)
Worker: 10.50.9.16
Worker: 10.50.9.16

```

**Comment by prablr79** [comment] 2018-10-29 08:46
@dockerciuser can you update the versions that you observed this issue ?

**Comment by dockerciuser** [comment] 2018-10-29 08:49
@prablr79 , 
Docker Engine - 17.06.2-ee-16
Kubernetes    - v1.8.11-docker-8d637ae
Volume plugin - master

**Comment by wdurairaj** [comment] 2018-11-07 12:03
I see the kubernetes controller has set the PV to lost state and then the doryd picks up the event and marks the PV in Lost state.

```
Oct 25 07:29:24 openshift-master-node1 origin-master-controllers: I1025 07:29:24.396211   16330 pv_controller.go:707] claim "default/pvc1-farhan" entered phase "Lost"
Oct 25 07:29:24 openshift-master-node1 doryd: 07:29:24 claim.go:96: updatedClaim: pvc pvc1-farhan current phase=Lost
Oct 25 07:29:24 openshift-master-node1 doryd: 07:29:24 provisioner.go:129: sendUpdate: pvc:pvc1-farhan (62984098-d848-11e8-b732-c4346bc12918) phase:Lost
```

**Comment by prablr79** [comment] 2018-11-08 06:10
Farhan is not able to reproduce this defect in the new setup. hence moving this to Medium

**Comment by prablr79** [comment] 2019-04-10 09:26
Virendra please check and come back if this issue still persist

**Comment by virendra-sharma** [comment] 2019-04-10 11:17
@prablr79 verified the issue and in both cases (static & dynamic provisioning) PV, PVC remains in bound state. It is not going in lost state.

Functionality is working now as expected, hence can close this issue.

Below is output of status after few minutes.
```
[root@CSSOSBE03-B07-Master ~]# kubectl get sc,pv,pvc,pod
NAME                      PROVISIONER
storageclasses/sc-test1   hpe.com/hpe

NAME                                               CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM               STORAGECLASS   REASON    AGE
pv/pv-test                                         35Gi       RWO            Retain           Bound     default/pvc-test                             18m
pv/sc-test1-f76531fc-5b7f-11e9-8ff2-0242ac11000a   10Gi       RWO            Delete           Bound     default/pvc-test1   sc-test1                 11m

NAME            STATUS    VOLUME                                          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc/pvc-test    Bound     pv-test                                         35Gi       RWO                           18m
pvc/pvc-test1   Bound     sc-test1-f76531fc-5b7f-11e9-8ff2-0242ac11000a   10Gi       RWO            sc-test1       11m

NAME           READY     STATUS    RESTARTS   AGE
po/pod-test    1/1       Running   0          17m
po/pod-test1   1/1       Running   0          11m
```

**Comment by wdurairaj** [comment] 2019-04-11 05:18
Closing based on previous comment. Thanks Virendra.

**Closed by wdurairaj** 2019-04-11 05:18 UTC
Labels: bug, medium
