### ISSUE TITLE
OpenShift 3.9 - Unable to create the PVC for scenario “without any driver option”

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#233] opened 2018-08-08 05:54 UTC
I tried to create the PVC without specifying any driver option.

Expected output - The PVC should be created with default size.
Actual output – The PVC is showing pending status.

[root@openshift-master-node1 ansible_3par_docker_plugin]# sudo oc create -f - << EOF
> ---
> kind: StorageClass
> apiVersion: storage.k8s.io/v1
> metadata:
>  name: sc1
> provisioner: hpe.com/hpe
> EOF
storageclass "sc1" created
[root@openshift-master-node1 ansible_3par_docker_plugin]# sudo oc create -f - << EOF
> ---
> kind: PersistentVolumeClaim
> apiVersion: v1
> metadata:
>   name: pvc2
> spec:
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: sc1
> EOF
The PersistentVolumeClaim "pvc2" is invalid: spec.resources[storage]: Required value
[root@openshift-master-node1 ansible_3par_docker_plugin]#
[root@openshift-master-node1 ansible_3par_docker_plugin]#
[root@openshift-master-node1 ansible_3par_docker_plugin]# sudo oc create -f - << EOF
> ---
> kind: PersistentVolumeClaim
> apiVersion: v1
> metadata:
>   name: pvc1
> spec:
>   accessModes:
>     - ReadWriteOnce
>   resources:
>     requests:
>       storage: 16Gi
>   storageClassName: sc1
> EOF
persistentvolumeclaim "pvc1" created
[root@openshift-master-node1 ansible_3par_docker_plugin]# oc get pvc
NAME      STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc1      Pending                                       sc1            7s

**Comment by dockerciuser** [comment] 2018-08-08 06:01
[messages_log_obs_1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2269102/messages_log_obs_1.txt)

**Comment by wdurairaj** [comment] 2018-09-27 17:27
StorageClass by definition it means as stated in kubernetes documentation
`A StorageClass provides a way for administrators to describe the “classes” of storage they offer`

Classes of storage is differentiated by only some change in the `parameters:` section of a storage class definition. So, creating a storageclass without parameters is not a generally widely used approach. 

Again i see the problem is kind of duplicate to one issue i raised in dory -- https://github.com/hpe-storage/dory/issues/32 

For now i'm marking this as low priority.

**Comment by wdurairaj** [comment] 2018-10-16 15:42
Based on the previous comment as justification to why we will not make a fix , I'm closing this issue.

**Closed by wdurairaj** 2018-10-16 15:42 UTC
Labels: bug, low
