### ISSUE TITLE
Docker EE 2.0 with UCP : Error in creating snapshot.

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#390] opened 2018-10-29 05:50 UTC
While creating the snapshot got an error due to size parameter.
Below are the detailed steps which I followed - 
1. Created storage class -
[root@CSSOSBE03-B11 new_yaml]# cat sc.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc
provisioner: hpe.com/hpe
parameters:
  size: "17"
[root@CSSOSBE03-B11 new_yaml]# kubectl create -f sc.yml
storageclass "test-sc" created
[root@CSSOSBE03-B11 new_yaml]# kubectl get sc
NAME           PROVISIONER
test-sc        hpe.com/hpe

2. Created PVC - 
[root@CSSOSBE03-B11 new_yaml]# cat pvc.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: test-sc
[root@CSSOSBE03-B11 new_yaml]# kubectl create -f pvc.yml
persistentvolumeclaim "pvc-test" created
[root@CSSOSBE03-B11 new_yaml]# docker volume ls
DRIVER              VOLUME NAME
hpe                 FP-VOLUME
hpe                 test-sc-9c1413bb-db39-11e8-a0ae-0242ac110010

3. Created new storage class required for snapshot - 

[root@CSSOSBE03-B11 new_yaml]# cat sc_2.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc-snp
provisioner: hpe.com/hpe
parameters:
  virtualCopyOf: test-sc-9c1413bb-db39-11e8-a0ae-0242ac110010
[root@CSSOSBE03-B11 new_yaml]# kubectl create -f sc_2.yml
storageclass "test-sc-snp" created

4. Tried to create PVC got an error - 

[root@CSSOSBE03-B11 new_yaml]# cat pvc_2.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test-snp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: test-sc-snp
 
ERROR - 

01:27:51 dockervol.go:267: unable to create docker volume using test-sc-snp-d2300f9a-db3a-11e8-a0ae-0242ac110010 & map[virtualCopyOf:test-sc-9c1413bb-db39-11e8-a0ae-0242ac110010 size:20 mountConflictDelay:30] - Invalid input received: Invalid option(s) ['size'] specified for operation create snapshot. Please check help for usage.

#### Removed the size parameter as  -

[root@CSSOSBE03-B11 new_yaml]# cat pvc_2.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test-snp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: test-sc-snp

ERROR - 

[root@CSSOSBE03-B11 new_yaml]# kubectl create -f pvc_2.yml
The PersistentVolumeClaim "pvc-test-snp" is invalid: spec.resources[storage]: Required value

#### The value of size parameter kept as blank (null)

[root@CSSOSBE03-B11 new_yaml]# cat pvc_2.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test-snp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:

ERROR - 

[root@CSSOSBE03-B11 new_yaml]# kubectl create -f pvc_2.yml
error: error validating "pvc_2.yml": error validating data: unknown object type "nil" in PersistentVolumeClaim.spec.resources.requests.storage; if you choose to ignore these errors, turn validation off with --validate=false

####  With the flag "validate=false" able to create the snapshot.

[root@CSSOSBE03-B11 new_yaml]# kubectl create -f pvc_2.yml --validate=false
persistentvolumeclaim "pvc-test-snp" created

[root@CSSOSBE03-B11 new_yaml]# docker volume ls
DRIVER              VOLUME NAME
hpe                 test-sc-9c1413bb-db39-11e8-a0ae-0242ac110010
hpe                 test-sc-snp-58a9c097-db3e-11e8-a0ae-0242ac110010

**Comment by imran-ansari** [comment] 2018-10-29 07:51
'size' parameter is not allowed for creating a snapshot. However, size parameter seems to be a requirement by K8S.
Since Tushar was able to work out his with with setting size to 0 and using --validate=false, I feel that this is a candidate for documentation issue.

**Comment by dockerciuser** [comment] 2018-10-29 08:30
Same behavior is seen while importing the volume.

**Comment by nilangekarss** [comment] 2018-10-29 08:50
@dockerciuser could you tell what is the size with which the snapshot gets created when size is not specified and marked validate==false?

**Comment by dockerciuser** [comment] 2018-10-29 08:56
@nilangekarss , The size of snapshot is same as the size of parent volume with flag validate=false

**Comment by dockerciuser** [comment] 2018-10-29 12:44
@nilangekarss 
Docker Engine - 17.06.2-ee-16
Kubernetes    - v1.8.11-docker-8d637ae

**Comment by nilangekarss** [comment] 2018-10-30 14:15
@imran-ansari @wdurairaj @prablr79 We should allow the size parameter to be passed along with the virtualCopyOf and Import in our plugin but this parameter is ignored inside the code. The PVC is associated with a StorageClass and PVC has a required parameter spec.resources[storage]. Clone accepts size which is specified during PVC creation hence we do not see any error while creating a clone of a volume. Hence due to the dependency on K8S, we should remove the restriction on size while creating snap, schedule, and import functionality.

**Comment by dockerciuser** [comment] 2018-11-15 15:57
This bug was raised while executing the tests on kubernetes 1.8.11. As a workaround we were able to create  snapshot / importVol with flag --validate=false
Now I saw same behavior on kubernetes 1.12, where this flag is also not working.

When tried to import volume got following error - 

[root@kuber-master STORAGE-CLASS]# kubectl create -f pvc-importvol.yaml --validate=false
The PersistentVolumeClaim "pvc-importvolsc" is invalid: spec.resources[storage]: Invalid value: "0": must be greater than zero

Used following YAMLS - 

[root@kuber-master STORAGE-CLASS]# cat  sc-importvol.yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc-importvolsc
provisioner: hpe.com/hpe
parameters:
  importVol: sample1
[root@kuber-master STORAGE-CLASS]#
[root@kuber-master STORAGE-CLASS]# cat  pvc-importvol.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-importvolsc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:
  storageClassName: sc-importvolsc


Now we cant create snapshot or import volume in kubernetes 1.12

**Comment by wdurairaj** [comment] 2018-11-15 20:16
@dockerciuser , @imran-ansari , i believe we can allow size in -o virtualCopyOf parameter in the request validator and in inside the code we have to ignore processing for size, since the snapshot size is same as that of volume size. Will this require a code fix.

**Comment by imran-ansari** [comment] 2018-11-16 00:05
Yes. Code fix + Documentation for Docker users.

**Comment by imran-ansari** [comment] 2018-11-16 00:30
I think this fix will be required for snapshot-schedule as well.

**Comment by imran-ansari** [comment] 2018-11-16 04:30
Ideally this needed to be fixed in Dory/Doryd

**Comment by wdurairaj** [comment] 2018-11-16 09:11
> Even for -o importVol size should be supported.

I totally forgot that this option will be used in a storageClass, 

1. Create storageClass s1
``
parameters:
   importVol: i1
```
2. When PVC based on above storage class s1
3. When a new PVC is again created, the volume creation will fail, since i1 is already renamed.

So, we should'nt ideally use this in a storageclass.

**Comment by dockerciuser** [comment] 2018-11-19 11:12
@wdurairaj @imran-ansari , I am able to create the snapshot with latest plugin. When tried to create the snapshot schedule got error.
Error log from DORY - 

05:44:53 dockervol.go:262: unable to create docker volume using sc-snapschedule-566bb67b-ebe7-11e8-917a-6cc21739c360 & map[virtualCopyOf:FC-VOLUME mountConflictDelay:30 scheduleFrequency:10 * * * * scheduleName:schedule-tushar snapshotPrefix:tushar] - Post http://unix/VolumeDriver.Create: http: ContentLength=217 with Body length 0 response - &{{  map[]} }
05:44:53 provisioner.go:520: failed to create docker volume, error = Post http://unix/VolumeDriver.Create: http: ContentLength=217 with Body length 0


The storage class YAML which I used is -
[root@kuber-master testing_size_parameter]# cat sc-snapSched.yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc-snapschedule
provisioner: hpe.com/hpe
parameters:
  name: snaptushar
  virtualCopyOf: FC-VOLUME
  scheduleFrequency: "10 * * * *"
  scheduleName: schedule-tushar
  snapshotPrefix: tushar
[root@kuber-master testing_size_parameter]#

**Comment by imran-ansari** [comment] 2018-11-19 11:16
Could you please check if you are able to create snapshot schedule directly using Docker with the same parameters?
Also please attach all the logs.

**Comment by wdurairaj** [comment] 2018-11-19 11:33
```
05:44:53 dockervol.go:262: unable to create docker volume using sc-snapschedule-566bb67b-ebe7-11e8-917a-6cc21739c360 & map[virtualCopyOf:FC-VOLUME mountConflictDelay:30 scheduleFrequency:10 * * * * scheduleName:schedule-tushar snapshotPrefix:tushar] - Post http://unix/VolumeDriver.Create: http: ContentLength=217 with Body length 0 response - &{{ map[]} }
```

I somewhat suspect the `scheduleFrequency:10 * * * *` which is not passed with double quotes in k8s environment.

**Comment by wdurairaj** [comment] 2018-11-19 12:20
Hi Tushar,

Can you check how this volume got created ?
```
[root@kuber-master testing_size_parameter]# docker volume ls
DRIVER              VOLUME NAME
hpe                 FC-VOLUME
hpe                 FC-VOLUME_SNAP
hpe                 FC-scheduling
hpe                 VOLUME
local               ed27581f9ec69055760c16874e680243624befae4d50d13b9bc8386c5f79430e
hpe                 sc-snapschedule-c85564f2-ebe2-11e8-917a-6cc21739c360
hpe                 sc-snapshot-b03b5b02-ebd8-11e8-917a-6cc21739c360
hpe                 sc-snapshot-sch-1f40a52f-ebdf-11e8-917a-6cc21739c360
hpe                 sc-snapshot2-f0f1c6a1-ebdf-11e8-917a-6cc21739c360
hpe                 tushar1235_qos_snap
[root@kuber-master testing_size_parameter]# docker volume inspect sc-snapschedule-c85564f2-ebe2-11e8-917a-6cc21739c360
[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "/",
        "Name": "sc-snapschedule-c85564f2-ebe2-11e8-917a-6cc21739c360",
        "Options": {},
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "3par_vol_name": "dcs-V4jKuKeOQS29UjiBphZR7A",
                "backend": "3PAR",
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "870ed217-4425-444b-b170-5c9b15536dce",
                "parent_volume": "FC-VOLUME",
                "provisioning": "thin",
                "retention_hours": null,
                "size": 100,
                "snap_cpg": "SHASHI-SSD",
                "snap_schedule": {
                    "sched_frequency": "20, * * * *",
                    "sched_snap_exp_hrs": null,
                    "sched_snap_ret_hrs": null,
                    "schedule_name": "schedule-tushar",
                    "snap_name_prefix": "tushar"
                }
            }
        }
    }
]
```
Is the above volume is created using a storage class ?

**Comment by wdurairaj** [comment] 2018-11-19 12:32
Actually as per my analysis, even scheduleName can used in a storage class for the same reason, we can't have `importVol`  , since 
1. when the first pvc is created with sc having `scheduleName`, this will succeed
2. when the second pvc is created again with sc having the same same schedulename as previous one, then the following error is thrown in the docker logs

```
2018-11-19 11:45:33.541 14 INFO hpedockerplugin.hpe.hpe_3par_common [-] Created a snapshot schedule - command is: ['createsched', '"createsv -f test_prefix.@y@@m@@d@@H@@M@@S@ dcv-hw7SF0QlREuxcFybFVNtzg"', '"10 6,8,10 * * *"', 'doc_schedule', '\r']...^[[00m
2018-11-19 11:45:33.541 14 INFO hpedockerplugin.hpe.hpe_3par_common [-] Create schedule response is: ['CSIM-8K02_MXN6072AC7 cli% createsched "createsv -f test_prefix.@y@@m@@d@@H@@M@@\r', 'S@ dcv-hw7SF0QlREuxcFybFVNtzg" "10 6,8,10 * * *" doc_schedule \r', 'Error: Scheduled task name: doc_schedule is already in use\r', '\r', 'CSIM-8K02_MXN6072AC7 cli% \r']...^[[00m
2018-11-19 11:45:33.541 14 ERROR hpedockerplugin.hpe.hpe_3par_common [-] Create snapschedule failed Error is 'Error: Scheduled task name: doc_schedule is already in use' ^[[00m
```
You can see the 'doc_schedule' already exists.

**Comment by wdurairaj** [comment] 2018-11-19 12:34
you can confirm the above theory, my creatig a new storageclass with schedulename as different from the already existing ones in 3par, but you will see only the first schedule based on a SC class will work correctly. So, it's an expected behaviour.

**Comment by dockerciuser** [comment] 2018-11-19 13:56
@wdurairaj , Did more experimentation. My observation is as - 

 -> You are right, the snapshot is created on 3PAR 
- > I can see it from docker side as well.

But the PVC status remains "pending"(Expecting as Bound) this bit confusing.

Also saw following error in dory logs - 

08:50:08 provisioner.go:237: statusLogger: provision chains=1, delete chains=0, parked chains=0, ids tracked=1, connection=valid
08:50:09 dockervol.go:262: unable to create docker volume using sc-sch-tushar-f1d54065-ec01-11e8-917a-6cc21739c360 & map[snapshotPrefix:tru virtualCopyOf:vol_test_sch mountConflictDelay:30 scheduleFrequency:10 * * * * scheduleName:trusch] - Post http://unix/VolumeDriver.Create: http: ContentLength=206 with Body length 0 response - &{{  map[]} }
08:50:09 provisioner.go:520: failed to create docker volume, error = Post http://unix/VolumeDriver.Create: http: ContentLength=206 with Body length 0
08:50:13 provisioner.go:237: statusLogger: provision chains=1, delete chains=0, parked chains=0, ids tracked=1, connection=valid

That means functionality is working as expected but it is giving the unwanted error and the " Pending " status.

**Comment by wdurairaj** [comment] 2018-11-19 14:54
I do agree with your statements @dockerciuser , But if we say our guideline would be to just use the snapshot scheduling only as part of static provisioning (as part of PV,POD only) and not relevant for dynamic provisioning (using SC) would that suffice ?

**Comment by prablr79** [comment] 2018-11-19 16:12
@dockerciuser @wdurairaj  are we thinking of fix here ? shall we live with the document for this scenario, how customer can handle this issue.  I believe other scenarios we are able to create the snapshot scheduling without any issues.. kindly confirm.

**Comment by nilangekarss** [comment] 2018-11-20 04:50
@dockerciuser @wdurairaj While creating a snapshot schedule we use ssh connection, if the ssh response from the array is slow the docker http client will timeout in 30 seconds. If the plugin is able to response in a proper manner in a limited time it is observed that snapshot schedule gets created properly. When we enable the plugin the default client http timeout is set to 30 seconds.
One way to overcome this issue of creating a snapshot schedule on an array which has good response for ssh connection Or we need to increase the time out of http client while enabling the plugin.

@dockerciuser , Tushar can you try creating a schedule on 3PAR array which has a good ssh response time? Also please try to create a schedule on a problematic array which has bad ssh response time. The response time of docker http client can be increased up to 2 min while enabling the plugin(But IT LOOKS like to be limited to only plugin enable).

I believe, when dory/plugin sends a error response while creating a pvc, it is expected for a pvc to go in a pending state. Please correct me if this is not a correct statement.

Few of the moby links:
Note: API timeout and plugin timeout are 2 different things.
https://docs.docker.com/engine/reference/commandline/plugin_enable/
https://github.com/moby/moby/issues/37426
https://github.com/moby/moby/issues/37835
https://github.com/moby/moby/pull/37908

**Comment by dockerciuser** [comment] 2018-11-20 12:46
Created the snapshot schedule successfully on Kubernetes setup with both the arrays 10.50.3.9 and 10.50.3.24.
Also I can see the status of PVC as “BOUND” and no exception in dory log.

1.	Removed the old dory binary.
2.	Removed the containerized plugin.
3.	Installed new binaries from  - https://github.com/hpe-storage/python-hpedockerplugin/raw/master/dory_installer
4.	Installed the latest plugin  - hpestorage/legacyvolumeplugin:3.0


YAMLS used – 

[root@kuber-master tushar]# cat sc_sch_tushar.yml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc-sch-tushar
provisioner: hpe.com/hpe
parameters:
 virtualCopyOf: SNAPSCH
 scheduleFrequency: "10 * * * *"
 scheduleName: SCHTESTING
 snapshotPrefix: SNAPSHOT
[root@kuber-master tushar]# cat pvc_sch_tushar.yml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sch-tushar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10
  storageClassName: sc-sch-tushar


Attaching the console output for the reference.
[final_scheduling_testing.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2599755/final_scheduling_testing.txt)

**Comment by wdurairaj** [comment] 2018-11-20 14:40
Based on Tushar's previous update, I'm closing this bug.

**Closed by wdurairaj** 2018-11-20 14:40 UTC
Labels: bug, medium
